# Pandas Notebook

Pandas is a Python library used for working with tabular data, similar to rows and columns in Excel.

In this notebook, we will use simple examples from an Indian context: customers, cities, orders, payments, and sales.

You will learn:
- How to create a DataFrame
- How to inspect data
- How to select rows and columns
- How to filter data
- How to add new columns
- How to group and summarize data
- How to handle missing values
- How to sort and merge data

In [1]:
!pip install pandas

Requirement already satisfied: pandas in ./.venv/lib/python3.9/site-packages (2.3.3)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.9/site-packages (from pandas) (2026.3)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.9/site-packages (from pandas) (2026.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: numpy>=1.22.4 in ./.venv/lib/python3.9/site-packages (from pandas) (2.0.2)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Users/rama/Desktop/BITSoM_Batch3/.venv/bin/python3 -m pip install --upgrade pip' command.

In [4]:
import pandas as pd

pd.set_option("display.max_columns", 20)
pd.set_option("display.precision", 2)

## 1. Create a DataFrame

A DataFrame is a table with rows and columns. Here is a small sales dataset for an Indian retail store.

In [5]:
sales_data = {
    "order_id": [101, 102, 103, 104, 105, 106, 107, 108],
    "customer": ["Aarav", "Diya", "Kabir", "Meera", "Ishaan", "Ananya", "Rohan", "Sara"],
    "city": ["Mumbai", "Delhi", "Bengaluru", "Chennai", "Mumbai", "Pune", "Delhi", "Hyderabad"],
    "product": ["Laptop", "Phone", "Headphones", "Tablet", "Phone", "Laptop", "Tablet", "Headphones"],
    "quantity": [1, 2, 3, 1, 1, 2, 2, 4],
    "price": [55000, 18000, 2500, 22000, 20000, 52000, 24000, 2200],
    "payment_mode": ["UPI", "Card", "UPI", "Cash", "UPI", "Net Banking", "Card", "UPI"]
}

sales = pd.DataFrame(sales_data)
sales

   order_id customer       city     product  quantity  price payment_mode
0       101    Aarav     Mumbai      Laptop         1  55000          UPI
1       102     Diya      Delhi       Phone         2  18000         Card
2       103    Kabir  Bengaluru  Headphones         3   2500          UPI
3       104    Meera    Chennai      Tablet         1  22000         Cash
4       105   Ishaan     Mumbai       Phone         1  20000          UPI
5       106   Ananya       Pune      Laptop         2  52000  Net Banking
6       107    Rohan      Delhi      Tablet         2  24000         Card
7       108     Sara  Hyderabad  Headphones         4   2200          UPI

## 2. Inspect the Data

These commands help us understand the shape, columns, and first few rows of a dataset.

In [10]:
sales.head(3)

   order_id customer       city     product  quantity  price payment_mode
0       101    Aarav     Mumbai      Laptop         1  55000          UPI
1       102     Diya      Delhi       Phone         2  18000         Card
2       103    Kabir  Bengaluru  Headphones         3   2500          UPI

In [11]:
sales.tail()

   order_id customer       city     product  quantity  price payment_mode
3       104    Meera    Chennai      Tablet         1  22000         Cash
4       105   Ishaan     Mumbai       Phone         1  20000          UPI
5       106   Ananya       Pune      Laptop         2  52000  Net Banking
6       107    Rohan      Delhi      Tablet         2  24000         Card
7       108     Sara  Hyderabad  Headphones         4   2200          UPI

In [13]:
sales.shape

(8, 7)

In [14]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      8 non-null      int64
 1   customer      8 non-null      object
 2   city          8 non-null      object
 3   product       8 non-null      object
 4   quantity      8 non-null      int64
 5   price         8 non-null      int64
 6   payment_mode  8 non-null      object
dtypes: int64(3), object(4)
memory usage: 576.0+ bytes

In [15]:
sales.describe()

       order_id  quantity     price
count      8.00      8.00      8.00
mean     104.50      2.00  24462.50
std        2.45      1.07  19772.92
min      101.00      1.00   2200.00
25%      102.75      1.00  14125.00
50%      104.50      2.00  21000.00
75%      106.25      2.25  31000.00
max      108.00      4.00  55000.00

## 3. Select Columns

Use square brackets to select one or more columns.

In [18]:
type(sales)

pandas.core.frame.DataFrame

In [17]:
type(sales["city"])

pandas.core.series.Series

In [19]:
column_needed=["customer", "city", "product"]
sales[column_needed]

  customer       city     product
0    Aarav     Mumbai      Laptop
1     Diya      Delhi       Phone
2    Kabir  Bengaluru  Headphones
3    Meera    Chennai      Tablet
4   Ishaan     Mumbai       Phone
5   Ananya       Pune      Laptop
6    Rohan      Delhi      Tablet
7     Sara  Hyderabad  Headphones

## 4. Select Rows with `loc` and `iloc`

- `loc` selects rows and columns using labels.
- `iloc` selects rows and columns using integer positions.

In [20]:
sales.loc[0, "customer"]

'Aarav'

In [22]:
column_needed=["customer", "city", "product"]
sales.loc[0:3, column_needed]

  customer       city     product
0    Aarav     Mumbai      Laptop
1     Diya      Delhi       Phone
2    Kabir  Bengaluru  Headphones
3    Meera    Chennai      Tablet

In [24]:
sales.iloc[0:3, 1:4]

  customer       city     product
0    Aarav     Mumbai      Laptop
1     Diya      Delhi       Phone
2    Kabir  Bengaluru  Headphones

## 5. Filter Rows

Filtering helps us answer questions such as: Which orders came from Delhi? Which orders were paid by UPI?

In [26]:
sales["city"]

0       Mumbai
1        Delhi
2    Bengaluru
3      Chennai
4       Mumbai
5         Pune
6        Delhi
7    Hyderabad
Name: city, dtype: object

In [25]:
sales["city"] == "Delhi"

0    False
1     True
2    False
3    False
4    False
5    False
6     True
7    False
Name: city, dtype: bool

In [27]:
condition = sales["city"] == "Delhi"
sales[condition]

   order_id customer   city product  quantity  price payment_mode
1       102     Diya  Delhi   Phone         2  18000         Card
6       107    Rohan  Delhi  Tablet         2  24000         Card

In [28]:
sales[sales["payment_mode"] == "UPI"]

   order_id customer       city     product  quantity  price payment_mode
0       101    Aarav     Mumbai      Laptop         1  55000          UPI
2       103    Kabir  Bengaluru  Headphones         3   2500          UPI
4       105   Ishaan     Mumbai       Phone         1  20000          UPI
7       108     Sara  Hyderabad  Headphones         4   2200          UPI

In [29]:
sales[sales["price"] > 20000]

   order_id customer     city product  quantity  price payment_mode
0       101    Aarav   Mumbai  Laptop         1  55000          UPI
3       104    Meera  Chennai  Tablet         1  22000         Cash
5       106   Ananya     Pune  Laptop         2  52000  Net Banking
6       107    Rohan    Delhi  Tablet         2  24000         Card

In [22]:
sales[(sales["city"] == "Mumbai") & (sales["payment_mode"] == "UPI")]

   order_id customer    city product  quantity  price payment_mode
0       101    Aarav  Mumbai  Laptop         1  55000          UPI
4       105   Ishaan  Mumbai   Phone         1  20000          UPI

## 6. Add New Columns

We can calculate the total order value using quantity and price.

In [30]:
sales["order_value"] = sales["quantity"] * sales["price"]
sales

,order_id,customer,city,product,quantity,price,payment_mode,order_value
0,101,Aarav,Mumbai,Laptop,1,55000,UPI,55000
1,102,Diya,Delhi,Phone,2,18000,Card,36000
2,103,Kabir,Bengaluru,Headphones,3,2500,UPI,7500
3,104,Meera,Chennai,Tablet,1,22000,Cash,22000
4,105,Ishaan,Mumbai,Phone,1,20000,UPI,20000
5,106,Ananya,Pune,Laptop,2,52000,Net Banking,104000
6,107,Rohan,Delhi,Tablet,2,24000,Card,48000
7,108,Sara,Hyderabad,Headphones,4,2200,UPI,8800

In [31]:
sales["gst_18_percent"] = sales["order_value"] * 0.18
sales["final_amount"] = sales["order_value"] + sales["gst_18_percent"]
sales

,order_id,customer,city,product,quantity,price,payment_mode,order_value,gst_18_percent,final_amount
0,101,Aarav,Mumbai,Laptop,1,55000,UPI,55000,9900.0,64900.0
1,102,Diya,Delhi,Phone,2,18000,Card,36000,6480.0,42480.0
2,103,Kabir,Bengaluru,Headphones,3,2500,UPI,7500,1350.0,8850.0
3,104,Meera,Chennai,Tablet,1,22000,Cash,22000,3960.0,25960.0
4,105,Ishaan,Mumbai,Phone,1,20000,UPI,20000,3600.0,23600.0
5,106,Ananya,Pune,Laptop,2,52000,Net Banking,104000,18720.0,122720.0
6,107,Rohan,Delhi,Tablet,2,24000,Card,48000,8640.0,56640.0
7,108,Sara,Hyderabad,Headphones,4,2200,UPI,8800,1584.0,10384.0

## 7. Sort Data

Sorting makes it easy to find the highest or lowest values.

In [25]:
sales.sort_values(by="final_amount", ascending=False)

,order_id,customer,city,product,quantity,price,payment_mode,order_value,gst_18_percent,final_amount
5,106,Ananya,Pune,Laptop,2,52000,Net Banking,104000,18720.0,122720.0
0,101,Aarav,Mumbai,Laptop,1,55000,UPI,55000,9900.0,64900.0
6,107,Rohan,Delhi,Tablet,2,24000,Card,48000,8640.0,56640.0
1,102,Diya,Delhi,Phone,2,18000,Card,36000,6480.0,42480.0
3,104,Meera,Chennai,Tablet,1,22000,Cash,22000,3960.0,25960.0
4,105,Ishaan,Mumbai,Phone,1,20000,UPI,20000,3600.0,23600.0
7,108,Sara,Hyderabad,Headphones,4,2200,UPI,8800,1584.0,10384.0
2,103,Kabir,Bengaluru,Headphones,3,2500,UPI,7500,1350.0,8850.0

## 8. Group and Summarize Data

`groupby` is useful for creating summaries such as sales by city or sales by payment mode.

In [26]:
sales.groupby("city")["final_amount"].sum()

city
Bengaluru      8850.0
Chennai       25960.0
Delhi         99120.0
Hyderabad     10384.0
Mumbai        88500.0
Pune         122720.0
Name: final_amount, dtype: float64

In [27]:
sales.groupby("payment_mode")["order_value"].mean()

payment_mode
Card            42000.0
Cash            22000.0
Net Banking    104000.0
UPI             22825.0
Name: order_value, dtype: float64

In [28]:
sales.groupby("product").agg(
    total_quantity=("quantity", "sum"),
    total_sales=("final_amount", "sum"),
    average_price=("price", "mean")
)

            total_quantity  total_sales  average_price
product
Headphones               7      19234.0         2350.0
Laptop                   3     187620.0        53500.0
Phone                    3      66080.0        19000.0
Tablet                   3      82600.0        23000.0

## 9. Missing Values

Real datasets often have missing values. Pandas represents missing values as `NaN`.

In [29]:
student_data = {
    "student": ["Arjun", "Neha", "Farhan", "Priya", "Tanya"],
    "city": ["Jaipur", "Kolkata", "Lucknow", None, "Ahmedabad"],
    "maths": [88, 92, None, 75, 81],
    "english": [79, None, 84, 90, 76]
}

students = pd.DataFrame(student_data)
students

  student       city  maths  english
0   Arjun     Jaipur   88.0     79.0
1    Neha    Kolkata   92.0      NaN
2  Farhan    Lucknow    NaN     84.0
3   Priya       None   75.0     90.0
4   Tanya  Ahmedabad   81.0     76.0

In [30]:
students.isna()

   student   city  maths  english
0    False  False  False    False
1    False  False  False     True
2    False  False   True    False
3    False   True  False    False
4    False  False  False    False

In [31]:
students.isna().sum()

student    0
city       1
maths      1
english    1
dtype: int64

In [ ]:
students_filled = students.copy()
students_filled["city"] = students_filled["city"].fillna("Unknown")
students_filled["maths"] = students_filled["maths"].fillna(students_filled["maths"].mean())
students_filled["english"] = students_filled["english"].fillna(students_filled["english"].mean())
students_filled

  student       city  maths  english
0   Arjun     Jaipur   88.0    79.00
1    Neha    Kolkata   92.0    82.25
2  Farhan    Lucknow   84.0    84.00
3   Priya    Unknown   75.0    90.00
4   Tanya  Ahmedabad   81.0    76.00

## 10. Merge DataFrames

Merging is like using VLOOKUP in Excel. We can combine data from two tables using a common column.

In [33]:
customers = pd.DataFrame({
    "customer": ["Aarav", "Diya", "Kabir", "Meera", "Ishaan", "Ananya", "Rohan", "Sara"],
    "loyalty_level": ["Gold", "Silver", "Bronze", "Silver", "Gold", "Bronze", "Silver", "Gold"]
})

customers

  customer loyalty_level
0    Aarav          Gold
1     Diya        Silver
2    Kabir        Bronze
3    Meera        Silver
4   Ishaan          Gold
5   Ananya        Bronze
6    Rohan        Silver
7     Sara          Gold

In [34]:
sales_with_loyalty = sales.merge(customers, on="customer", how="left")
sales_with_loyalty

,order_id,customer,city,product,quantity,price,payment_mode,order_value,gst_18_percent,final_amount,loyalty_level
0,101,Aarav,Mumbai,Laptop,1,55000,UPI,55000,9900.0,64900.0,Gold
1,102,Diya,Delhi,Phone,2,18000,Card,36000,6480.0,42480.0,Silver
2,103,Kabir,Bengaluru,Headphones,3,2500,UPI,7500,1350.0,8850.0,Bronze
3,104,Meera,Chennai,Tablet,1,22000,Cash,22000,3960.0,25960.0,Silver
4,105,Ishaan,Mumbai,Phone,1,20000,UPI,20000,3600.0,23600.0,Gold
5,106,Ananya,Pune,Laptop,2,52000,Net Banking,104000,18720.0,122720.0,Bronze
6,107,Rohan,Delhi,Tablet,2,24000,Card,48000,8640.0,56640.0,Silver
7,108,Sara,Hyderabad,Headphones,4,2200,UPI,8800,1584.0,10384.0,Gold

## 11. Export Data

Use `to_csv` to save a DataFrame as a CSV file. The file will be created in the same folder as this notebook.

In [35]:
sales_with_loyalty.to_csv("indian_sales_summary.csv", index=False)

## 12. Using `map()` and `apply()`

`map()` is commonly used on one column to replace or convert values.

`apply()` is used when we want to run a custom function on a column or across rows.

### `map()` Example

Let us map each payment mode to a simple payment category.

In [36]:
payment_category = {
    "UPI": "Digital",
    "Card": "Digital",
    "Net Banking": "Digital",
    "Cash": "Offline"
}

sales["payment_category"] = sales["payment_mode"].map(payment_category)
sales[["customer", "payment_mode", "payment_category"]]

  customer payment_mode payment_category
0    Aarav          UPI          Digital
1     Diya         Card          Digital
2    Kabir          UPI          Digital
3    Meera         Cash          Offline
4   Ishaan          UPI          Digital
5   Ananya  Net Banking          Digital
6    Rohan         Card          Digital
7     Sara          UPI          Digital

### `apply()` on One Column

Here we create a price band for each product price.

In [37]:
def price_band(price):
    if price >= 50000:
        return "Premium"
    elif price >= 20000:
        return "Mid Range"
    else:
        return "Budget"

sales["price_band"] = sales["price"].apply(price_band)
sales[["product", "price", "price_band"]]

      product  price price_band
0      Laptop  55000    Premium
1       Phone  18000     Budget
2  Headphones   2500     Budget
3      Tablet  22000  Mid Range
4       Phone  20000  Mid Range
5      Laptop  52000    Premium
6      Tablet  24000  Mid Range
7  Headphones   2200     Budget

### `apply()` Across Rows

Use `axis=1` when the function needs values from multiple columns in the same row.

In [38]:
def delivery_speed(row):
    if row["city"] in ["Mumbai", "Delhi", "Bengaluru"] and row["payment_category"] == "Digital":
        return "Fast Delivery"
    else:
        return "Standard Delivery"

sales["delivery_type"] = sales.apply(delivery_speed, axis=1)
sales[["customer", "city", "payment_category", "delivery_type"]]

  customer       city payment_category      delivery_type
0    Aarav     Mumbai          Digital      Fast Delivery
1     Diya      Delhi          Digital      Fast Delivery
2    Kabir  Bengaluru          Digital      Fast Delivery
3    Meera    Chennai          Offline  Standard Delivery
4   Ishaan     Mumbai          Digital      Fast Delivery
5   Ananya       Pune          Digital  Standard Delivery
6    Rohan      Delhi          Digital      Fast Delivery
7     Sara  Hyderabad          Digital  Standard Delivery